{
    "adult": False,
    "also_known_as": [
        "Кристофер Нолан",
        "Крістофер Нолан",
        "克里斯托弗·诺兰",
        "คริสโตเฟอร์ โนแลน",
        "クリストファー・ノーラン",
        "كريستوفر نولان",
        "크리스토퍼 놀란",
        "Κρίστοφερ Νόλαν",
        "Christopher Edward Nolan",
        "כריסטופר נולאן",
    ],
    "biography": "Chris stopher Edward Nolan, CBE (born 30 July 1970) is a British-American film director, screenwriter, and producer. He was born in Westminster, London, England and holds both British and American citizenship due to his American mother. He is known for writing and directing critically acclaimed films such as Memento (2000), The Prestige (2006), The Dark Knight Trilogy (2005-12), Inception (2010), Interstellar (2014) and Dunkirk (2017). Nolan is the founder of the production company Syncopy Films. He often collaborates with his wife, producer Emma Thomas, and his brother, screenwriter Jonathan Nolan.",
    "birthday": "1970-07-30",
    "deathday": None,
    "gender": 2,
    "homepage": None,
    "id": 525,
    "imdb_id": "nm0634240",
    "known_for_department": "Directing",
    "name": "Christopher Nolan",
    "place_of_birth": "Westminster, London, England, UK",
    "popularity": 30.125,
    "profile_path": "/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg",
    "movie_credits": {
        "cast": [
            {
                "adult": False,
                "backdrop_path": "/v6EUsxCZBksSmcomBcXErJZWL2I.jpg",
                "genre_ids": [99],
                "id": 186567,
                "original_language": "en",
                "original_title": "Gotham Uncovered: Creation of a Scene",
                "overview": "Director Christopher Nolan and creative collaborators unmask the incredible detail and planning behind The Dark Knight, including stunt staging, filming in IMAX, the new Bat-Suit and Bat-Pod and other exclusive features.",
                "popularity": 1.544,
                "poster_path": "/lAAwYAEnDXJoYt1V0DUBkLJK8sh.jpg",
                "release_date": "2008-07-15",
                "title": "Gotham Uncovered: Creation of a Scene",
                "video": False,
                "vote_average": 7.0,
                "vote_count": 8,
                "character": "Self",
                "credit_id": "52fe4d009251416c7512c917",
                "order": 0,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 529107,
                "original_language": "en",
                "original_title": "Inside 'Interstellar'",
                "overview": "Cast and crew of Christopher Nolan's \"Interstellar\" discuss project origins, the film's imagery, ambitions, incorporating IMAX footage, the human element within the film, arm shooting locations outside of Calgary, the set construction and design, working with real corn, mechanical characters, including backstory, design, the blend of practical and digital effects in bringing them to life, the differences in the characters, the human performances behind the characters, the creative process behind the film's music, Icelandic locations, vehicle interiors, the processes of simulating the absence of gravity, the crucial end-film visuals and influence and inspiration for future generations",
                "popularity": 11.424,
                "poster_path": "/vemBplPKQhVe5cRWL7kxtgp15Vq.jpg",
                "release_date": "2015-03-31",
                "title": "Inside 'Interstellar'",
                "video": False,
                "vote_average": 7.0,
                "vote_count": 9,
                "character": "Self - Director / Co-Writer",
                "credit_id": "5b1bcc479251414bc60213eb",
                "order": 0,
            },
            {
                "adult": False,
                "backdrop_path": "/5kPQ2cW5aXtUweJiabgK8lg732o.jpg",
                "genre_ids": [99],
                "id": 790331,
                "original_language": "en",
                "original_title": "Looking at the World in a New Way: The Making of 'Tenet'",
                "overview": "A look behind the scenes of Christopher Nolan's Tenet.",
                "popularity": 3.492,
                "poster_path": "/mwj189nph5bM0lc4fsjbEjI8V5M.jpg",
                "release_date": "2020-12-15",
                "title": "Looking at the World in a New Way: The Making of 'Tenet'",
                "video": False,
                "vote_average": 8.6,
                "vote_count": 7,
                "character": "Self",
                "credit_id": "609b859b8dbc33006e323a14",
                "order": 0,
            },
            {
                "adult": False,
                "backdrop_path": "/9PnKdVpdC7HaNjQLKPygHMT637e.jpg",
                "genre_ids": [99],
                "id": 29751,
                "original_language": "en",
                "original_title": "Batman Unmasked: The Psychology of 'The Dark Knight'",
                "overview": "Delve into the world of Batman and the vigilante justice that he brought to the city of Gotham. Batman is a man who, after experiencing great tragedy, devotes his life to an ideal--but what happens when one man takes on the evil underworld alone? Examine why Batman is who he is--and explore how a boy scarred by tragedy becomes a symbol of hope to everyone else.",
                "popularity": 12.08,
                "poster_path": "/e15wNHmLX7PJUo8lqzQRhwbX7PL.jpg",
                "release_date": "2008-07-15",
                "title": "Batman Unmasked: The Psychology of 'The Dark Knight'",
                "video": False,
                "vote_average": 7.433,
                "vote_count": 44,
                "character": "Self",
                "credit_id": "52fe45f7c3a368484e0793e9",
                "order": 1,
            },
            {
                "adult": False,
                "backdrop_path": "/bOc2eQBSeRI2fHoAVCtm3yaA0e6.jpg",
                "genre_ids": [99],
                "id": 186579,
                "original_language": "en",
                "original_title": "Batman Tech",
                "overview": "He's caped, cowled and the coolest superhero of them all, because underneath that Batsuit, Batman only has his human strength and intellect to rely on. That and the greatest arsenal of crime fighting weaponry ever devised. But just where does comic book science fiction end and scientific fact begin? What technologies are behind the gadgets in Batman's utility belt? And just how plausible is the Batmobile? Get ready for a real life trip to the Batcave as we reveal the secrets behind Batman Tech.",
                "popularity": 8.173,
                "poster_path": "/tlAYMNTvga69AUXMIY0HeeoblHT.jpg",
                "release_date": "2008-07-21",
                "title": "Batman Tech",
                "video": False,
                "vote_average": 7.0,
                "vote_count": 18,
                "character": "Self",
                "credit_id": "52fe4d009251416c7512c9cd",
                "order": 1,
            },
            {
                "adult": False,
                "backdrop_path": "/et9lB7MV2liUNkXCLbdrPlE2Pr1.jpg",
                "genre_ids": [99],
                "id": 416813,
                "original_language": "en",
                "original_title": "Cinema Futures",
                "overview": "The “digital revolution” reached the cinema late and was chiefly styled as a technological advancement. Today, in an era where analog celluloid strips are disappearing, and given the diversity of digital moving picture formats, there is much more at stake: Are the world’s film archives on the brink of a dark age? Are we facing the massive loss of collective audiovisual memory? Is film dying, or just changing? CINEMA FUTURES travels to international locations and, together with renowned filmmakers, museum curators, historians and engineers, dramatizes the future of film and the cinema in the age of digital moving pictures.",
                "popularity": 1.243,
                "poster_path": "/f2Pih9muBJMhqFCNmw1b64mMFVd.jpg",
                "release_date": "2016-09-02",
                "title": "Cinema Futures",
                "video": False,
                "vote_average": 6.2,
                "vote_count": 4,
                "character": "",
                "credit_id": "57e017cac3a3681dc800a07c",
                "order": 1,
            },
            {
                "adult": False,
                "backdrop_path": "/qcx2OKadBD1abBsKRObHJvryvF0.jpg",
                "genre_ids": [10770, 27],
                "id": 804706,
                "original_language": "en",
                "original_title": "Tarantella",
                "overview": '"Tarantella" was an early Super 8 short film directed by Christopher Nolan with his childhood friend Roko Belic. It was made in 1989 while Nolan was studying at University College London. The film aired on "Image Union," a PBS programme in Chicago.  It is about the suffering of a young man while he has nightmare about spiders and demons.',
                "popularity": 3.682,
                "poster_path": "/7BJzoe7zCgZ3ADROZ4Ix4ycyD3S.jpg",
                "release_date": "1990-09-12",
                "title": "Tarantella",
                "video": False,
                "vote_average": 5.143,
                "vote_count": 21,
                "character": "Man in Black",
                "credit_id": "62d21e78b3316b004f86c4b4",
                "order": 1,
            },
            {
                "adult": False,
                "backdrop_path": "/t0bea3HLfxSllBdZy90UxrXl260.jpg",
                "genre_ids": [99],
                "id": 1152711,
                "original_language": "en",
                "original_title": "Inside Christopher Nolan's Oppenheimer",
                "overview": 'A look behind the scenes of Christopher Nolan\'s film "Oppenheimer" about an American scientist and his role in the development of the atomic bomb.',
                "popularity": 37.255,
                "poster_path": "/iEQQrq61v6oAtFbJ7Ym3ie5bdKA.jpg",
                "release_date": "2023-07-15",
                "title": "Inside Christopher Nolan's Oppenheimer",
                "video": False,
                "vote_average": 3.0,
                "vote_count": 1,
                "character": "Self - Director / Writer / Producer",
                "credit_id": "64b3ce2d78570e00c6d4cdc2",
                "order": 1,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 712602,
                "original_language": "en",
                "original_title": "The Making of 'Dunkirk'",
                "overview": '"Dunkirk" opens as hundreds of thousands of British and Allied troops are surrounded by enemy forces. Trapped on the beach with their backs to the sea they face an impossible situation as the enemy closes in.',
                "popularity": 2.562,
                "poster_path": "/vh0CDKOazJIHgtD2g58ZSyEG9aS.jpg",
                "release_date": "2017-12-09",
                "title": "The Making of 'Dunkirk'",
                "video": False,
                "vote_average": 7.857,
                "vote_count": 14,
                "character": "Self",
                "credit_id": "5ed9c3a581a7fc001ecf4422",
                "order": 2,
            },
            {
                "adult": False,
                "backdrop_path": "/lv606WMZ9iZpIo6o3yeIVDAEBOl.jpg",
                "genre_ids": [99, 36],
                "id": 1149947,
                "original_language": "en",
                "original_title": "To End All War: Oppenheimer & the Atomic Bomb",
                "overview": "Explore how one man's relentless drive and invention of the atomic bomb changed the nature of war forever, led to the deaths of hundreds of thousands of people and unleashed mass hysteria.",
                "popularity": 98.851,
                "poster_path": "/xwkYWcs8aypUtk3xDRUh0ndo4GA.jpg",
                "release_date": "2023-07-09",
                "title": "To End All War: Oppenheimer & the Atomic Bomb",
                "video": False,
                "vote_average": 7.739,
                "vote_count": 109,
                "character": 'Self - Writer / Director, "Oppenheimer"',
                "credit_id": "64aaeb9b6a344800ea8cbd95",
                "order": 2,
            },
            {
                "adult": False,
                "backdrop_path": "/jytx4eZkkWzffZzsCkmWztKex0w.jpg",
                "genre_ids": [99],
                "id": 334931,
                "original_language": "en",
                "original_title": "Dreams: Cinema of the Subconscious",
                "overview": 'Can the dream world be a fully functional parallel reality? Joseph Gordon-Levitt and leading scientists take you to the cutting edge of dream research in this documentary produced for Christopher Nolan\'s "Inception."',
                "popularity": 2.648,
                "poster_path": "/ijz2HzG87GdkRuPK51FYfdG4naR.jpg",
                "release_date": "2010-12-07",
                "title": "Dreams: Cinema of the Subconscious",
                "video": False,
                "vote_average": 6.875,
                "vote_count": 8,
                "character": "Self",
                "credit_id": "64bbfc8eeb79c200e28d070c",
                "order": 2,
            },
            {
                "adult": False,
                "backdrop_path": "/NqfD4QFzSqr3fFnS4GtTMZEz2E.jpg",
                "genre_ids": [99, 10402, 10770],
                "id": 1031907,
                "original_language": "en",
                "original_title": "Hans Zimmer: Hollywood Rebel",
                "overview": "An in-depth look of the 40 year journey, from post-war Germany to Hollywood royalty, of Hans Zimmer, the man who’s become the dominant force in the world of movie soundtracks. His film credits include The Lion King, Rain Man, Pirates of The Caribbean, Gladiator, The Dark Knight, Batman Begins, 12 Year A Slave, The Thin Red Line, The Da Vinci Code and Dune.",
                "popularity": 1.578,
                "poster_path": "/e6eFWrSjkzXSDTliRonCX7P504K.jpg",
                "release_date": "2022-10-16",
                "title": "Hans Zimmer: Hollywood Rebel",
                "video": False,
                "vote_average": 7.8,
                "vote_count": 5,
                "character": "Self",
                "credit_id": "633cd7064df291007d6d1bea",
                "order": 3,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 227585,
                "original_language": "en",
                "original_title": "Tales from the Warner Bros. Lot",
                "overview": "Actors, crew and executives who worked at Warner Bros. Pictures recall their days at the studio.",
                "popularity": 1.4,
                "poster_path": "/k1Q1ayXdOb6H1emGtnGGwy63uPU.jpg",
                "release_date": "2013-01-15",
                "title": "Tales from the Warner Bros. Lot",
                "video": False,
                "vote_average": 5.5,
                "vote_count": 2,
                "character": "Self",
                "credit_id": "52fe4ea99251416c7515e023",
                "order": 4,
            },
            {
                "adult": False,
                "backdrop_path": "/13vViuBMtgPaUEZCJSHztbCYaUN.jpg",
                "genre_ids": [99],
                "id": 595841,
                "original_language": "en",
                "original_title": "Making Waves: The Art of Cinematic Sound",
                "overview": "An exploration of the history, artistry and emotional power of cinema sound, as revealed by legendary sound designers and visionary directors, via interviews, clips from movies, and a look at their actual process of creation and discovery.",
                "popularity": 9.149,
                "poster_path": "/uZ9K2ElWpFcfvwUK4DoDVPteK2z.jpg",
                "release_date": "2019-10-25",
                "title": "Making Waves: The Art of Cinematic Sound",
                "video": False,
                "vote_average": 6.7,
                "vote_count": 55,
                "character": "Self",
                "credit_id": "5cc85b3a0e0a263743f13ad8",
                "order": 4,
            },
            {
                "adult": False,
                "backdrop_path": "/vc4BgDe25zwpdOm9908MAvjb3PU.jpg",
                "genre_ids": [99],
                "id": 243238,
                "original_language": "en",
                "original_title": "The Fire Rises: The Creation and Impact of The Dark Knight Trilogy",
                "overview": "This feature-length documentary delves into the trilogy, opening with the inspiration and vision for the new Batman films and inching its way toward the Rises finale and the culmination of nearly a decade of creative blood, sweat and tears. Candid, thoughtful and extensive, and comprised of revealing behind-the-scenes footage, countless interviews, audition tapes (with Christian Bale and Cillian Murphy doning the cape and cowl), and a narrative grip and momentum all its own, it leaves no stone unturned.",
                "popularity": 5.944,
                "poster_path": "/kVlpamukelm5HkZES50b6F61UfX.jpg",
                "release_date": "2013-09-24",
                "title": "The Fire Rises: The Creation and Impact of The Dark Knight Trilogy",
                "video": False,
                "vote_average": 6.972,
                "vote_count": 18,
                "character": "Self",
                "credit_id": "52fe4edbc3a36847f82ac56d",
                "order": 5,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 315470,
                "original_language": "en",
                "original_title": "Stanley Kubrick in Focus",
                "overview": "Spielberg, Soderbergh, Stone, Friedkin, Scorsese and others tell how Kubrick's directorial style influenced them and how his unique style was developed.",
                "popularity": 1.4,
                "poster_path": None,
                "release_date": "2012-11-30",
                "title": "Stanley Kubrick in Focus",
                "video": False,
                "vote_average": 6.0,
                "vote_count": 4,
                "character": "Self",
                "credit_id": "5684525f92514113340100c2",
                "order": 5,
            },
            {
                "adult": False,
                "backdrop_path": "/fTcs5ejlN1MwwLSSv9aU1mi5alL.jpg",
                "genre_ids": [99],
                "id": 301959,
                "original_language": "en",
                "original_title": "Interstellar: Nolan's Odyssey",
                "overview": "A look behind the lens of Christopher Nolan's space epic.",
                "popularity": 26.181,
                "poster_path": "/i4PpBcuLvdcJwIf3hkcV9QDR1iH.jpg",
                "release_date": "2014-11-05",
                "title": "Interstellar: Nolan's Odyssey",
                "video": False,
                "vote_average": 7.699,
                "vote_count": 166,
                "character": "Self",
                "credit_id": "545fc288c3a3680b5a000ebd",
                "order": 6,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 292790,
                "original_language": "en",
                "original_title": "Exploring 'The Tree of Life'",
                "overview": 'A documentary on Terrence Malick and the making of his film "The Tree of Life."',
                "popularity": 1.4,
                "poster_path": None,
                "release_date": "2011-10-11",
                "title": "Exploring 'The Tree of Life'",
                "video": False,
                "vote_average": 5.8,
                "vote_count": 5,
                "character": "Self",
                "credit_id": "59c77710c3a368141e04fa31",
                "order": 8,
            },
            {
                "adult": False,
                "backdrop_path": "/puznYtHv2zsZfRKWZbdqb9GrbgT.jpg",
                "genre_ids": [99],
                "id": 80337,
                "original_language": "en",
                "original_title": "These Amazing Shadows",
                "overview": "Tells the history and importance of The National Film Registry, a roll call of American cinema treasures that reflects the diversity of film, and indeed the American experience itself.",
                "popularity": 4.361,
                "poster_path": "/jiby8Ilxlmbhv6elIf0qRMuaDdd.jpg",
                "release_date": "2011-01-22",
                "title": "These Amazing Shadows",
                "video": False,
                "vote_average": 7.429,
                "vote_count": 63,
                "character": "Self",
                "credit_id": "52fe47b99251416c91073b03",
                "order": 10,
            },
            {
                "adult": False,
                "backdrop_path": "/oaYnpllVVB3o5qIlPoACFfWJz6K.jpg",
                "genre_ids": [99],
                "id": 311998,
                "original_language": "en",
                "original_title": "Film Noir: Bringing Darkness to Light",
                "overview": "Film Noir burrows into the mind; it's disorienting, intriguing and enthralling. Noir brings us into a gritty underworld of lush morbidity, providing intimate peeks at its tough, scheming dames, mischievous misfits and flawed men - all caught in the wicked web of a twisted fate.",
                "popularity": 2.099,
                "poster_path": "/djInrUsSdM1ZDRS9WsE4MgKwEqT.jpg",
                "release_date": "2006-07-18",
                "title": "Film Noir: Bringing Darkness to Light",
                "video": False,
                "vote_average": 7.1,
                "vote_count": 13,
                "character": "Self",
                "credit_id": "5c4965e20e0a263ccdcdf8dd",
                "order": 11,
            },
            {
                "adult": False,
                "backdrop_path": "/AkuDVdvopWHr2Vw3IBmfhlPk8Bx.jpg",
                "genre_ids": [99],
                "id": 110354,
                "original_language": "en",
                "original_title": "Side by Side",
                "overview": "Since the invention of cinema, the standard format for recording moving images has been film. Over the past two decades, a new form of digital filmmaking has emerged, creating a groundbreaking evolution in the medium. Keanu Reeves explores the development of cinema and the impact of digital filmmaking via in-depth interviews with Hollywood masters, such as James Cameron, David Fincher, David Lynch, Christopher Nolan, Martin Scorsese, George Lucas, Steven Soderbergh, and many more.",
                "popularity": 11.901,
                "poster_path": "/qeeQ7rfTAXNYh4EqqdolFLkNwKM.jpg",
                "release_date": "2012-08-19",
                "title": "Side by Side",
                "video": False,
                "vote_average": 7.263,
                "vote_count": 263,
                "character": "Self",
                "credit_id": "52fe4ad2c3a36847f81e393d",
                "order": 12,
            },
            {
                "adult": False,
                "backdrop_path": "/49aEh5Gmlkk1BGlzFgvbcMOgsIL.jpg",
                "genre_ids": [99],
                "id": 125231,
                "original_language": "en",
                "original_title": "The Batmobile",
                "overview": "Witness all five Batmobiles together for the first time in history. Dive deep into every aspect of the most awe-inspiring weapon in Batman’s arsenal as you journey through the birth and evolution of this technological marvel and cultural icon",
                "popularity": 2.08,
                "poster_path": "/2ntILBHp9SIa8nXMwPmswD0H3M4.jpg",
                "release_date": "2012-07-16",
                "title": "The Batmobile",
                "video": False,
                "vote_average": 6.75,
                "vote_count": 22,
                "character": "Self",
                "credit_id": "52fe4abfc3a368484e164c6b",
                "order": 13,
            },
            {
                "adult": False,
                "backdrop_path": "/mTOrGSfDC7CmZBtN8FVGDrSfaNB.jpg",
                "genre_ids": [],
                "id": 126444,
                "original_language": "en",
                "original_title": "Cinema16: British Short Films",
                "overview": "This critically acclaimed DVD contains 16 of the best classic and award winning British short films and delivers a snapshot of British cinema past and present. It includes films from Britain's most exciting new talent alongside early shorts from it's most successful filmmakers' amongst them Chris Nolan (Memento, Insomnia, Batman Begins), Ridley Scott (Gladiator, Alien), Mike Leigh (Secrets and Lies) and Stephen Daldry (Billy Elliot, The Hours).\r 01 About a Girl - Brian Percival\r 02 Boy & Bicycle - Ridley Scott\r 03 Dear Phone - Peter Greenaway\r 04 Doodlebug - Christopher Nolan\r 05 Eight - Stephen Daldry\r 06 Gasman - Lynne Ramsay\r 07 Girl Chewing Gum - John Smith\r 08 Home - Morag McKinnon\r 09 Joyride - Jim Gillespie\r 10 Inside Out - Tom & Charles Guard\r 11 Je T\x92aime John Wayne - Toby Macdonald\r 12 The Sheep Thief - Asif Kapadia\r 13 The Short & Curlies - Mike Leigh\r 14 Telling Lies - Simon Ellis\r 15 UK Images - Martin Parr\r 16 Who\x92s My Favourite Girl? - Adrian J. McDowall",
                "popularity": 1.02,
                "poster_path": "/iY1FDQM6taKwO7bG6YH09nE8NSs.jpg",
                "release_date": "2003-05-05",
                "title": "Cinema16: British Short Films",
                "video": True,
                "vote_average": 4.6,
                "vote_count": 5,
                "character": "Self - Commentary, Doodlebug (voice)",
                "credit_id": "634ea135a8b2ca007e4f5d9c",
                "order": 14,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 789323,
                "original_language": "en",
                "original_title": "Heath Ledger: A Tribute",
                "overview": "On January 22, 2008, the entertainment world was rocked by news that one of its brightest young stars had unexpectedly died. This film is a commemorative special dedicated to the life and works of this complex and unique talent who died before his time.",
                "popularity": 4.581,
                "poster_path": "/x1eJojaMe9N0y0qg5yRRWEjYJxa.jpg",
                "release_date": "2009-06-01",
                "title": "Heath Ledger: A Tribute",
                "video": False,
                "vote_average": 10.0,
                "vote_count": 2,
                "character": "Self",
                "credit_id": "61cabbccb6c2640042d3a872",
                "order": 18,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 703363,
                "original_language": "en",
                "original_title": "Ending the Knight",
                "overview": 'A comprehensive look into how Director Christopher Nolan and his production team made "The Dark Knight Rises" the epic conclusion to the Dark Knight legend. These cover stunts and action, production/vehicle design, various effects, photography and shooting IMAX, sets and locations, sound design and music, story/character areas, cast and performances, and some general thoughts about the series.',
                "popularity": 7.132,
                "poster_path": "/2j9gMIbtftm26CbH78nIwiImoN0.jpg",
                "release_date": "2012-12-04",
                "title": "Ending the Knight",
                "video": False,
                "vote_average": 6.87,
                "vote_count": 23,
                "character": "Self",
                "credit_id": "5ebb2123c3514c002061d1c4",
                "order": 24,
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [99],
                "id": 829707,
                "original_language": "en",
                "original_title": "Catwoman: The Feline Femme Fatale",
                "overview": "A documentary about the history of Catwoman from DC.",
                "popularity": 2.338,
                "poster_path": "/ord8gdBUFitBHccX1S5RpatulA7.jpg",
                "release_date": "2021-05-05",
                "title": "Catwoman: The Feline Femme Fatale",
                "video": False,
                "vote_average": 8.5,
                "vote_count": 8,
                "character": "Self",
                "credit_id": "60b57cc4a61de1003fc1712d",
                "order": 27,
            },
            {
                "adult": False,
                "backdrop_path": "/212dUHxXRdjylPqx3a3xIGtzjl9.jpg",
                "genre_ids": [99],
                "id": 734586,
                "original_language": "en",
                "original_title": "Joker: Put on a Happy Face",
                "overview": "Featuring interviews with filmmakers and industry legends, discover the origins and evolution of The Joker, and learn why The Clown Prince of Crime is universally hailed as the greatest comic-book supervillain of all time.",
                "popularity": 6.97,
                "poster_path": "/am5Sst8LFmU0bhPrzU3km4RRy3J.jpg",
                "release_date": "2020-08-18",
                "title": "Joker: Put on a Happy Face",
                "video": False,
                "vote_average": 8.514,
                "vote_count": 37,
                "character": "Self",
                "credit_id": "5f3d323b9653f600369f56d6",
                "order": 28,
            },
            {
                "adult": False,
                "backdrop_path": "/tagkWNpQASfO7TNUVFfgCLZZ1Qe.jpg",
                "genre_ids": [99],
                "id": 50056,
                "original_language": "en",
                "original_title": "Secret Origin: The Story of DC Comics",
                "overview": "A look at the history of the comic book publication that launched such legendary characters as Superman, Batman and Wonder Woman.",
                "popularity": 4.697,
                "poster_path": "/bi4k7EE8JFuTHKWhiWEgdIlp40Z.jpg",
                "release_date": "2010-11-09",
                "title": "Secret Origin: The Story of DC Comics",
                "video": False,
                "vote_average": 7.0,
                "vote_count": 37,
                "character": "Self (archive footage)",
                "credit_id": "609032cfa097dc00791c0c3f",
                "order": 45,
            },
        ],
        "crew": [
            {
                "adult": False,
                "backdrop_path": "/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg",
                "genre_ids": [53, 14, 9648],
                "id": 43629,
                "original_language": "en",
                "original_title": "Doodlebug",
                "overview": "In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.",
                "popularity": 7.565,
                "poster_path": "/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg",
                "release_date": "1997-01-01",
                "title": "Doodlebug",
                "video": False,
                "vote_average": 6.5,
                "vote_count": 416,
                "credit_id": "595e4934c3a368265d085a8f",
                "department": "Art",
                "job": "Set Designer",
            },
            {
                "adult": False,
                "backdrop_path": "/owgFkvnozNYdShynerDjot2hHK2.jpg",
                "genre_ids": [18, 53],
                "id": 11660,
                "original_language": "en",
                "original_title": "Following",
                "overview": "Bill, an idle, unemployed aspiring writer, walks the crowded streets of London following randomly chosen strangers, a seemingly innocent entertainment that becomes dangerous when he crosses paths with a mysterious character.",
                "popularity": 14.331,
                "poster_path": "/3bX6VVSMf0dvzk5pMT4ALG5A92d.jpg",
                "release_date": "1999-04-02",
                "title": "Following",
                "video": False,
                "vote_average": 7.149,
                "vote_count": 1378,
                "credit_id": "52fe44739251416c75035321",
                "department": "Camera",
                "job": "Director of Photography",
            },
            {
                "adult": False,
                "backdrop_path": "/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg",
                "genre_ids": [99],
                "id": 352114,
                "original_language": "en",
                "original_title": "Quay",
                "overview": 'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                "popularity": 5.486,
                "poster_path": "/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg",
                "release_date": "2015-08-19",
                "title": "Quay",
                "video": False,
                "vote_average": 6.058,
                "vote_count": 52,
                "credit_id": "5ad78d7dc3a368719c000d42",
                "department": "Camera",
                "job": "Director of Photography",
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [18, 53, 35],
                "id": 456684,
                "original_language": "en",
                "original_title": "Larceny",
                "overview": "A man breaks into a flat, startling the occupant. They argue about the new girlfriend of the 'burglar', who's come  to get her stuff. Then a third man bursts out of the cupboard...",
                "popularity": 2.29,
                "poster_path": "/uL0iqPb4dtICVCCMKYem2yRPBRX.jpg",
                "release_date": "1996-07-14",
                "title": "Larceny",
                "video": False,
                "vote_average": 5.7,
                "vote_count": 7,
                "credit_id": "5e83ae2b24f2ce00187106ad",
                "department": "Camera",
                "job": "Director of Photography",
            },
            {
                "adult": False,
                "backdrop_path": "/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg",
                "genre_ids": [53, 14, 9648],
                "id": 43629,
                "original_language": "en",
                "original_title": "Doodlebug",
                "overview": "In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.",
                "popularity": 7.565,
                "poster_path": "/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg",
                "release_date": "1997-01-01",
                "title": "Doodlebug",
                "video": False,
                "vote_average": 6.5,
                "vote_count": 416,
                "credit_id": "5e83ae11c86b3a0011a73d94",
                "department": "Camera",
                "job": "Director of Photography",
            },
            {
                "adult": False,
                "backdrop_path": "/qcx2OKadBD1abBsKRObHJvryvF0.jpg",
                "genre_ids": [10770, 27],
                "id": 804706,
                "original_language": "en",
                "original_title": "Tarantella",
                "overview": '"Tarantella" was an early Super 8 short film directed by Christopher Nolan with his childhood friend Roko Belic. It was made in 1989 while Nolan was studying at University College London. The film aired on "Image Union," a PBS programme in Chicago.  It is about the suffering of a young man while he has nightmare about spiders and demons.',
                "popularity": 3.682,
                "poster_path": "/7BJzoe7zCgZ3ADROZ4Ix4ycyD3S.jpg",
                "release_date": "1990-09-12",
                "title": "Tarantella",
                "video": False,
                "vote_average": 5.143,
                "vote_count": 21,
                "credit_id": "604a191aec455200457de3b1",
                "department": "Camera",
                "job": "Director of Photography",
            },
            {
                "adult": False,
                "backdrop_path": "/lv606WMZ9iZpIo6o3yeIVDAEBOl.jpg",
                "genre_ids": [99, 36],
                "id": 1149947,
                "original_language": "en",
                "original_title": "To End All War: Oppenheimer & the Atomic Bomb",
                "overview": "Explore how one man's relentless drive and invention of the atomic bomb changed the nature of war forever, led to the deaths of hundreds of thousands of people and unleashed mass hysteria.",
                "popularity": 98.851,
                "poster_path": "/xwkYWcs8aypUtk3xDRUh0ndo4GA.jpg",
                "release_date": "2023-07-09",
                "title": "To End All War: Oppenheimer & the Atomic Bomb",
                "video": False,
                "vote_average": 7.739,
                "vote_count": 109,
                "credit_id": "64b2e5a40e4fc8011e0631c4",
                "department": "Crew",
                "job": "Thanks",
            },
            {
                "adult": False,
                "backdrop_path": "/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg",
                "genre_ids": [53, 14, 9648],
                "id": 43629,
                "original_language": "en",
                "original_title": "Doodlebug",
                "overview": "In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.",
                "popularity": 7.565,
                "poster_path": "/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg",
                "release_date": "1997-01-01",
                "title": "Doodlebug",
                "video": False,
                "vote_average": 6.5,
                "vote_count": 416,
                "credit_id": "5e83ae1b24f2ce00137104f0",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [18],
                "id": 505819,
                "original_language": "en",
                "original_title": "Cinema 16: European Short Films (U.S. Edition)",
                "overview": "A collection of short films by 16 European directors.",
                "popularity": 0.632,
                "poster_path": "/rQ884232vYo3pbm0Ov1bCrMy6Zp.jpg",
                "release_date": "2007-09-25",
                "title": "Cinema 16: European Short Films (U.S. Edition)",
                "video": True,
                "vote_average": 6.0,
                "vote_count": 1,
                "credit_id": "5e83acc86e3b68001864b90b",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/jU8MC5uSgBkZXyZYGtZgMsMsfeN.jpg",
                "genre_ids": [80, 9648, 53],
                "id": 320,
                "original_language": "en",
                "original_title": "Insomnia",
                "overview": "Two Los Angeles homicide detectives are dispatched to a northern town where the sun doesn't set to investigate the methodical murder of a local teen.",
                "popularity": 23.839,
                "poster_path": "/riVXh3EimGO0y5dgQxEWPRy5Itg.jpg",
                "release_date": "2002-05-24",
                "title": "Insomnia",
                "video": False,
                "vote_average": 6.936,
                "vote_count": 4229,
                "credit_id": "5e83ad2e24f2ce0018710514",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/pbrkL804c8yAv3zBZR4QPEafpAR.jpg",
                "genre_ids": [12, 18, 878],
                "id": 157336,
                "original_language": "en",
                "original_title": "Interstellar",
                "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
                "popularity": 251.393,
                "poster_path": "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                "release_date": "2014-11-05",
                "title": "Interstellar",
                "video": False,
                "vote_average": 8.412,
                "vote_count": 32207,
                "credit_id": "5e83abfad236e60017fd99ed",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/q2CtXYjp9IlnfBcPktNkBPsuAEO.jpg",
                "genre_ids": [9648, 53],
                "id": 77,
                "original_language": "en",
                "original_title": "Memento",
                "overview": "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
                "popularity": 35.808,
                "poster_path": "/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
                "release_date": "2000-10-11",
                "title": "Memento",
                "video": False,
                "vote_average": 8.189,
                "vote_count": 13574,
                "credit_id": "5e83ad65e33f83001435a709",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
                "genre_ids": [18, 28, 80, 53],
                "id": 155,
                "original_language": "en",
                "original_title": "The Dark Knight",
                "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                "popularity": 97.428,
                "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                "release_date": "2008-07-14",
                "title": "The Dark Knight",
                "video": False,
                "vote_average": 8.511,
                "vote_count": 30351,
                "credit_id": "5e83ac8b6e3b68001464b691",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
                "genre_ids": [28, 878, 12],
                "id": 27205,
                "original_language": "en",
                "original_title": "Inception",
                "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
                "popularity": 112.336,
                "poster_path": "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
                "release_date": "2010-07-15",
                "title": "Inception",
                "video": False,
                "vote_average": 8.364,
                "vote_count": 34276,
                "credit_id": "5e83ac2ee33f830018359a00",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/lh5lbisD4oDbEKgUxoRaZU8HVrk.jpg",
                "genre_ids": [28, 80, 18],
                "id": 272,
                "original_language": "en",
                "original_title": "Batman Begins",
                "overview": "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
                "popularity": 69.916,
                "poster_path": "/4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg",
                "release_date": "2005-06-10",
                "title": "Batman Begins",
                "video": False,
                "vote_average": 7.699,
                "vote_count": 19408,
                "credit_id": "5e83acf488bbe60018a69a1e",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/owgFkvnozNYdShynerDjot2hHK2.jpg",
                "genre_ids": [18, 53],
                "id": 11660,
                "original_language": "en",
                "original_title": "Following",
                "overview": "Bill, an idle, unemployed aspiring writer, walks the crowded streets of London following randomly chosen strangers, a seemingly innocent entertainment that becomes dangerous when he crosses paths with a mysterious character.",
                "popularity": 14.331,
                "poster_path": "/3bX6VVSMf0dvzk5pMT4ALG5A92d.jpg",
                "release_date": "1999-04-02",
                "title": "Following",
                "video": False,
                "vote_average": 7.149,
                "vote_count": 1378,
                "credit_id": "5e83adef6e3b68001464b8fc",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [18, 53, 35],
                "id": 456684,
                "original_language": "en",
                "original_title": "Larceny",
                "overview": "A man breaks into a flat, startling the occupant. They argue about the new girlfriend of the 'burglar', who's come  to get her stuff. Then a third man bursts out of the cupboard...",
                "popularity": 2.29,
                "poster_path": "/uL0iqPb4dtICVCCMKYem2yRPBRX.jpg",
                "release_date": "1996-07-14",
                "title": "Larceny",
                "video": False,
                "vote_average": 5.7,
                "vote_count": 7,
                "credit_id": "5e83ae34e33f83001435a7f0",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg",
                "genre_ids": [28, 53, 878],
                "id": 577922,
                "original_language": "en",
                "original_title": "Tenet",
                "overview": "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                "popularity": 67.382,
                "poster_path": "/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
                "release_date": "2020-08-22",
                "title": "Tenet",
                "video": False,
                "vote_average": 7.196,
                "vote_count": 8596,
                "credit_id": "5e83abdcd236e60015fd9f9f",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/xBDE2d6HM1aBKQRu4IT7SfPD9fs.jpg",
                "genre_ids": [18, 9648, 878],
                "id": 1124,
                "original_language": "en",
                "original_title": "The Prestige",
                "overview": "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
                "popularity": 51.64,
                "poster_path": "/gcphM7ZLxS5HPeCZgjZobfz907x.jpg",
                "release_date": "2006-10-19",
                "title": "The Prestige",
                "video": False,
                "vote_average": 8.202,
                "vote_count": 14530,
                "credit_id": "5e83ad1888bbe60013a69c6b",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg",
                "genre_ids": [99],
                "id": 352114,
                "original_language": "en",
                "original_title": "Quay",
                "overview": 'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                "popularity": 5.486,
                "poster_path": "/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg",
                "release_date": "2015-08-19",
                "title": "Quay",
                "video": False,
                "vote_average": 6.058,
                "vote_count": 52,
                "credit_id": "5e83ac7688bbe60015a69864",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/ddIkmH3TpR6XSc47jj0BrGK5Rbz.jpg",
                "genre_ids": [10752, 28, 18],
                "id": 374720,
                "original_language": "en",
                "original_title": "Dunkirk",
                "overview": "The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.",
                "popularity": 48.368,
                "poster_path": "/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
                "release_date": "2017-07-19",
                "title": "Dunkirk",
                "video": False,
                "vote_average": 7.456,
                "vote_count": 15341,
                "credit_id": "5e83ab8fe33f830018359941",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/2PKMeD171nYXR3J77fD3GKl1zfl.jpg",
                "genre_ids": [28, 80, 18, 53],
                "id": 49026,
                "original_language": "en",
                "original_title": "The Dark Knight Rises",
                "overview": "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                "popularity": 89.834,
                "poster_path": "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
                "release_date": "2012-07-16",
                "title": "The Dark Knight Rises",
                "video": False,
                "vote_average": 7.778,
                "vote_count": 21187,
                "credit_id": "6044f4f8c4ad590058f9c3fd",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/qcx2OKadBD1abBsKRObHJvryvF0.jpg",
                "genre_ids": [10770, 27],
                "id": 804706,
                "original_language": "en",
                "original_title": "Tarantella",
                "overview": '"Tarantella" was an early Super 8 short film directed by Christopher Nolan with his childhood friend Roko Belic. It was made in 1989 while Nolan was studying at University College London. The film aired on "Image Union," a PBS programme in Chicago.  It is about the suffering of a young man while he has nightmare about spiders and demons.',
                "popularity": 3.682,
                "poster_path": "/7BJzoe7zCgZ3ADROZ4Ix4ycyD3S.jpg",
                "release_date": "1990-09-12",
                "title": "Tarantella",
                "video": False,
                "vote_average": 5.143,
                "vote_count": 21,
                "credit_id": "604a18d9ea37e0002ad295de",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
                "genre_ids": [18, 36],
                "id": 872585,
                "original_language": "en",
                "original_title": "Oppenheimer",
                "overview": "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
                "popularity": 811.11,
                "poster_path": "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
                "release_date": "2023-07-19",
                "title": "Oppenheimer",
                "video": False,
                "vote_average": 8.265,
                "vote_count": 2088,
                "credit_id": "613a93cbd38b58005f6a1964",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/mTOrGSfDC7CmZBtN8FVGDrSfaNB.jpg",
                "genre_ids": [],
                "id": 126444,
                "original_language": "en",
                "original_title": "Cinema16: British Short Films",
                "overview": "This critically acclaimed DVD contains 16 of the best classic and award winning British short films and delivers a snapshot of British cinema past and present. It includes films from Britain's most exciting new talent alongside early shorts from it's most successful filmmakers' amongst them Chris Nolan (Memento, Insomnia, Batman Begins), Ridley Scott (Gladiator, Alien), Mike Leigh (Secrets and Lies) and Stephen Daldry (Billy Elliot, The Hours).\r 01 About a Girl - Brian Percival\r 02 Boy & Bicycle - Ridley Scott\r 03 Dear Phone - Peter Greenaway\r 04 Doodlebug - Christopher Nolan\r 05 Eight - Stephen Daldry\r 06 Gasman - Lynne Ramsay\r 07 Girl Chewing Gum - John Smith\r 08 Home - Morag McKinnon\r 09 Joyride - Jim Gillespie\r 10 Inside Out - Tom & Charles Guard\r 11 Je T\x92aime John Wayne - Toby Macdonald\r 12 The Sheep Thief - Asif Kapadia\r 13 The Short & Curlies - Mike Leigh\r 14 Telling Lies - Simon Ellis\r 15 UK Images - Martin Parr\r 16 Who\x92s My Favourite Girl? - Adrian J. McDowall",
                "popularity": 1.02,
                "poster_path": "/iY1FDQM6taKwO7bG6YH09nE8NSs.jpg",
                "release_date": "2003-05-05",
                "title": "Cinema16: British Short Films",
                "video": True,
                "vote_average": 4.6,
                "vote_count": 5,
                "credit_id": "634e9d3189f7490082e26b33",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "backdrop_path": "/owgFkvnozNYdShynerDjot2hHK2.jpg",
                "genre_ids": [18, 53],
                "id": 11660,
                "original_language": "en",
                "original_title": "Following",
                "overview": "Bill, an idle, unemployed aspiring writer, walks the crowded streets of London following randomly chosen strangers, a seemingly innocent entertainment that becomes dangerous when he crosses paths with a mysterious character.",
                "popularity": 14.331,
                "poster_path": "/3bX6VVSMf0dvzk5pMT4ALG5A92d.jpg",
                "release_date": "1999-04-02",
                "title": "Following",
                "video": False,
                "vote_average": 7.149,
                "vote_count": 1378,
                "credit_id": "52fe44739251416c7503532d",
                "department": "Editing",
                "job": "Editor",
            },
            {
                "adult": False,
                "backdrop_path": "/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg",
                "genre_ids": [53, 14, 9648],
                "id": 43629,
                "original_language": "en",
                "original_title": "Doodlebug",
                "overview": "In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.",
                "popularity": 7.565,
                "poster_path": "/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg",
                "release_date": "1997-01-01",
                "title": "Doodlebug",
                "video": False,
                "vote_average": 6.5,
                "vote_count": 416,
                "credit_id": "52fe4655c3a36847f80f96cf",
                "department": "Editing",
                "job": "Editor",
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [18, 53, 35],
                "id": 456684,
                "original_language": "en",
                "original_title": "Larceny",
                "overview": "A man breaks into a flat, startling the occupant. They argue about the new girlfriend of the 'burglar', who's come  to get her stuff. Then a third man bursts out of the cupboard...",
                "popularity": 2.29,
                "poster_path": "/uL0iqPb4dtICVCCMKYem2yRPBRX.jpg",
                "release_date": "1996-07-14",
                "title": "Larceny",
                "video": False,
                "vote_average": 5.7,
                "vote_count": 7,
                "credit_id": "595e4635c3a368265d085744",
                "department": "Editing",
                "job": "Editor",
            },
            {
                "adult": False,
                "backdrop_path": "/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg",
                "genre_ids": [99],
                "id": 352114,
                "original_language": "en",
                "original_title": "Quay",
                "overview": 'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                "popularity": 5.486,
                "poster_path": "/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg",
                "release_date": "2015-08-19",
                "title": "Quay",
                "video": False,
                "vote_average": 6.058,
                "vote_count": 52,
                "credit_id": "5f66865ae04d8a003a2c84d5",
                "department": "Editing",
                "job": "Editor",
            },
            {
                "adult": False,
                "backdrop_path": "/qcx2OKadBD1abBsKRObHJvryvF0.jpg",
                "genre_ids": [10770, 27],
                "id": 804706,
                "original_language": "en",
                "original_title": "Tarantella",
                "overview": '"Tarantella" was an early Super 8 short film directed by Christopher Nolan with his childhood friend Roko Belic. It was made in 1989 while Nolan was studying at University College London. The film aired on "Image Union," a PBS programme in Chicago.  It is about the suffering of a young man while he has nightmare about spiders and demons.',
                "popularity": 3.682,
                "poster_path": "/7BJzoe7zCgZ3ADROZ4Ix4ycyD3S.jpg",
                "release_date": "1990-09-12",
                "title": "Tarantella",
                "video": False,
                "vote_average": 5.143,
                "vote_count": 21,
                "credit_id": "604a1920c8a5ac006f002fd7",
                "department": "Editing",
                "job": "Editor",
            },
            {
                "adult": False,
                "backdrop_path": "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
                "genre_ids": [18, 28, 80, 53],
                "id": 155,
                "original_language": "en",
                "original_title": "The Dark Knight",
                "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                "popularity": 97.428,
                "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                "release_date": "2008-07-14",
                "title": "The Dark Knight",
                "video": False,
                "vote_average": 8.511,
                "vote_count": 30351,
                "credit_id": "52fe421fc3a36847f8005ce1",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/owgFkvnozNYdShynerDjot2hHK2.jpg",
                "genre_ids": [18, 53],
                "id": 11660,
                "original_language": "en",
                "original_title": "Following",
                "overview": "Bill, an idle, unemployed aspiring writer, walks the crowded streets of London following randomly chosen strangers, a seemingly innocent entertainment that becomes dangerous when he crosses paths with a mysterious character.",
                "popularity": 14.331,
                "poster_path": "/3bX6VVSMf0dvzk5pMT4ALG5A92d.jpg",
                "release_date": "1999-04-02",
                "title": "Following",
                "video": False,
                "vote_average": 7.149,
                "vote_count": 1378,
                "credit_id": "52fe44739251416c75035309",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
                "genre_ids": [28, 878, 12],
                "id": 27205,
                "original_language": "en",
                "original_title": "Inception",
                "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
                "popularity": 112.336,
                "poster_path": "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
                "release_date": "2010-07-15",
                "title": "Inception",
                "video": False,
                "vote_average": 8.364,
                "vote_count": 34276,
                "credit_id": "52fe4534c3a368484e04de2d",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/2PKMeD171nYXR3J77fD3GKl1zfl.jpg",
                "genre_ids": [28, 80, 18, 53],
                "id": 49026,
                "original_language": "en",
                "original_title": "The Dark Knight Rises",
                "overview": "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                "popularity": 89.834,
                "poster_path": "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
                "release_date": "2012-07-16",
                "title": "The Dark Knight Rises",
                "video": False,
                "vote_average": 7.778,
                "vote_count": 21187,
                "credit_id": "52fe4781c3a36847f8139893",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg",
                "genre_ids": [28, 12, 878],
                "id": 49521,
                "original_language": "en",
                "original_title": "Man of Steel",
                "overview": "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.",
                "popularity": 77.65,
                "poster_path": "/dksTL9NXc3GqPBRHYHcy1aIwjS.jpg",
                "release_date": "2013-06-12",
                "title": "Man of Steel",
                "video": False,
                "vote_average": 6.612,
                "vote_count": 14229,
                "credit_id": "52fe4799c3a36847f813e613",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/pbrkL804c8yAv3zBZR4QPEafpAR.jpg",
                "genre_ids": [12, 18, 878],
                "id": 157336,
                "original_language": "en",
                "original_title": "Interstellar",
                "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
                "popularity": 251.393,
                "poster_path": "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                "release_date": "2014-11-05",
                "title": "Interstellar",
                "video": False,
                "vote_average": 8.412,
                "vote_count": 32207,
                "credit_id": "52fe4bbf9251416c910e47ed",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/jis0J9GstjkrmtivoVAdSTc1pFi.jpg",
                "genre_ids": [53, 878, 18, 9648],
                "id": 157353,
                "original_language": "en",
                "original_title": "Transcendence",
                "overview": "Two leading computer scientists work toward their goal of Technological Singularity,  as a radical anti-technology organization fights to prevent them from creating a world where computers can transcend the abilities of the human brain.",
                "popularity": 22.45,
                "poster_path": "/qmOKJWl3wnXDcLhjtJHnCCCvAiO.jpg",
                "release_date": "2014-04-16",
                "title": "Transcendence",
                "video": False,
                "vote_average": 6.026,
                "vote_count": 5075,
                "credit_id": "52fe4bc19251416c910e4aef",
                "department": "Production",
                "job": "Executive Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/5fX1oSGuYdKgwWmUTAN5MNSQGzr.jpg",
                "genre_ids": [28, 12, 14],
                "id": 209112,
                "original_language": "en",
                "original_title": "Batman v Superman: Dawn of Justice",
                "overview": "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
                "popularity": 72.748,
                "poster_path": "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
                "release_date": "2016-03-23",
                "title": "Batman v Superman: Dawn of Justice",
                "video": False,
                "vote_average": 5.95,
                "vote_count": 16991,
                "credit_id": "553bf2ba925141125600a15d",
                "department": "Production",
                "job": "Executive Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/xBDE2d6HM1aBKQRu4IT7SfPD9fs.jpg",
                "genre_ids": [18, 9648, 878],
                "id": 1124,
                "original_language": "en",
                "original_title": "The Prestige",
                "overview": "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
                "popularity": 51.64,
                "poster_path": "/gcphM7ZLxS5HPeCZgjZobfz907x.jpg",
                "release_date": "2006-10-19",
                "title": "The Prestige",
                "video": False,
                "vote_average": 8.202,
                "vote_count": 14530,
                "credit_id": "5674abdac3a368167a000dd2",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/ddIkmH3TpR6XSc47jj0BrGK5Rbz.jpg",
                "genre_ids": [10752, 28, 18],
                "id": 374720,
                "original_language": "en",
                "original_title": "Dunkirk",
                "overview": "The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.",
                "popularity": 48.368,
                "poster_path": "/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
                "release_date": "2017-07-19",
                "title": "Dunkirk",
                "video": False,
                "vote_average": 7.456,
                "vote_count": 15341,
                "credit_id": "56cd9e759251415cda002182",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [18, 53, 35],
                "id": 456684,
                "original_language": "en",
                "original_title": "Larceny",
                "overview": "A man breaks into a flat, startling the occupant. They argue about the new girlfriend of the 'burglar', who's come  to get her stuff. Then a third man bursts out of the cupboard...",
                "popularity": 2.29,
                "poster_path": "/uL0iqPb4dtICVCCMKYem2yRPBRX.jpg",
                "release_date": "1996-07-14",
                "title": "Larceny",
                "video": False,
                "vote_average": 5.7,
                "vote_count": 7,
                "credit_id": "595e46199251410b8608adc6",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg",
                "genre_ids": [99],
                "id": 352114,
                "original_language": "en",
                "original_title": "Quay",
                "overview": 'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                "popularity": 5.486,
                "poster_path": "/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg",
                "release_date": "2015-08-19",
                "title": "Quay",
                "video": False,
                "vote_average": 6.058,
                "vote_count": 52,
                "credit_id": "595e478a925141225106bdac",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/2nyaeISu2xIxIgZYNpX4UayY8PN.jpg",
                "genre_ids": [28, 12, 878],
                "id": 141052,
                "original_language": "en",
                "original_title": "Justice League",
                "overview": "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
                "popularity": 78.939,
                "poster_path": "/eifGNCSDuxJeS1loAXil5bIGgvC.jpg",
                "release_date": "2017-11-15",
                "title": "Justice League",
                "video": False,
                "vote_average": 6.096,
                "vote_count": 12196,
                "credit_id": "5a0e066c92514138f0000db6",
                "department": "Production",
                "job": "Executive Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg",
                "genre_ids": [28, 53, 878],
                "id": 577922,
                "original_language": "en",
                "original_title": "Tenet",
                "overview": "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                "popularity": 67.382,
                "poster_path": "/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
                "release_date": "2020-08-22",
                "title": "Tenet",
                "video": False,
                "vote_average": 7.196,
                "vote_count": 8596,
                "credit_id": "5da457b01967570011acf8d5",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/wgVBPD10YEENLqVKcT1cYb4plJH.jpg",
                "genre_ids": [16, 18, 14],
                "id": 622678,
                "original_language": "en",
                "original_title": "The Doll's Breath",
                "overview": "Afraid of losing his wife, Horatio creates a replica he calls Hortensia. But things don't go as planned...\r Shot on 35mm and propelled by an impressive score by Michèle Bokanowski, the Quay Brothers evoke an intense drama of jealousy, betrayal and murder, revolving around a window dresser's obsession for a life-sized doll.",
                "popularity": 1.4,
                "poster_path": "/c0kaZzzx8wpKrx2mC20z4W1Tz3n.jpg",
                "release_date": "2019-09-11",
                "title": "The Doll's Breath",
                "video": False,
                "vote_average": 0.0,
                "vote_count": 0,
                "credit_id": "5f673f2edbcade00362954d7",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg",
                "genre_ids": [28, 12, 14],
                "id": 791373,
                "original_language": "en",
                "original_title": "Zack Snyder's Justice League",
                "overview": "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
                "popularity": 143.202,
                "poster_path": "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
                "release_date": "2021-03-18",
                "title": "Zack Snyder's Justice League",
                "video": False,
                "vote_average": 8.196,
                "vote_count": 9112,
                "credit_id": "601461580816c70042848352",
                "department": "Production",
                "job": "Executive Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/qcx2OKadBD1abBsKRObHJvryvF0.jpg",
                "genre_ids": [10770, 27],
                "id": 804706,
                "original_language": "en",
                "original_title": "Tarantella",
                "overview": '"Tarantella" was an early Super 8 short film directed by Christopher Nolan with his childhood friend Roko Belic. It was made in 1989 while Nolan was studying at University College London. The film aired on "Image Union," a PBS programme in Chicago.  It is about the suffering of a young man while he has nightmare about spiders and demons.',
                "popularity": 3.682,
                "poster_path": "/7BJzoe7zCgZ3ADROZ4Ix4ycyD3S.jpg",
                "release_date": "1990-09-12",
                "title": "Tarantella",
                "video": False,
                "vote_average": 5.143,
                "vote_count": 21,
                "credit_id": "604a191254508d007759e03a",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
                "genre_ids": [18, 36],
                "id": 872585,
                "original_language": "en",
                "original_title": "Oppenheimer",
                "overview": "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
                "popularity": 811.11,
                "poster_path": "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
                "release_date": "2023-07-19",
                "title": "Oppenheimer",
                "video": False,
                "vote_average": 8.265,
                "vote_count": 2088,
                "credit_id": "6140dd58aaf89700421a6dd1",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "backdrop_path": "/ArBSyfVp4oEaDPJjkDPebEZu0KD.jpg",
                "genre_ids": [99],
                "id": 352114,
                "original_language": "en",
                "original_title": "Quay",
                "overview": 'In 2015, Christopher Nolan curated a selection of short films by the surrealist animators the Quay Brothers to be distributed as a touring 35mm presentation. The three films—"In Absentia" (2000), "The Comb" (1991) and "Street of Crocodiles" (1986)—were accompanied by this brief portrait of the brothers at work in their London studio.',
                "popularity": 5.486,
                "poster_path": "/uluMeKfYFVvfZlmHgFBXqbnHXE2.jpg",
                "release_date": "2015-08-19",
                "title": "Quay",
                "video": False,
                "vote_average": 6.058,
                "vote_count": 52,
                "credit_id": "5ad78d90c3a3687196000dad",
                "department": "Sound",
                "job": "Original Music Composer",
            },
            {
                "adult": False,
                "backdrop_path": "/q2CtXYjp9IlnfBcPktNkBPsuAEO.jpg",
                "genre_ids": [9648, 53],
                "id": 77,
                "original_language": "en",
                "original_title": "Memento",
                "overview": "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
                "popularity": 35.808,
                "poster_path": "/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg",
                "release_date": "2000-10-11",
                "title": "Memento",
                "video": False,
                "vote_average": 8.189,
                "vote_count": 13574,
                "credit_id": "52fe4214c3a36847f80024d1",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "backdrop_path": "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
                "genre_ids": [18, 28, 80, 53],
                "id": 155,
                "original_language": "en",
                "original_title": "The Dark Knight",
                "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                "popularity": 97.428,
                "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                "release_date": "2008-07-14",
                "title": "The Dark Knight",
                "video": False,
                "vote_average": 8.511,
                "vote_count": 30351,
                "credit_id": "52fe4220c3a36847f8005d03",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "backdrop_path": "/lh5lbisD4oDbEKgUxoRaZU8HVrk.jpg",
                "genre_ids": [28, 80, 18],
                "id": 272,
                "original_language": "en",
                "original_title": "Batman Begins",
                "overview": "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
                "popularity": 69.916,
                "poster_path": "/4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg",
                "release_date": "2005-06-10",
                "title": "Batman Begins",
                "video": False,
                "vote_average": 7.699,
                "vote_count": 19408,
                "credit_id": "557c5dddc3a368632b001e9f",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "backdrop_path": "/xBDE2d6HM1aBKQRu4IT7SfPD9fs.jpg",
                "genre_ids": [18, 9648, 878],
                "id": 1124,
                "original_language": "en",
                "original_title": "The Prestige",
                "overview": "A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.",
                "popularity": 51.64,
                "poster_path": "/gcphM7ZLxS5HPeCZgjZobfz907x.jpg",
                "release_date": "2006-10-19",
                "title": "The Prestige",
                "video": False,
                "vote_average": 8.202,
                "vote_count": 14530,
                "credit_id": "52fe42e8c3a36847f802bef9",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "backdrop_path": "/owgFkvnozNYdShynerDjot2hHK2.jpg",
                "genre_ids": [18, 53],
                "id": 11660,
                "original_language": "en",
                "original_title": "Following",
                "overview": "Bill, an idle, unemployed aspiring writer, walks the crowded streets of London following randomly chosen strangers, a seemingly innocent entertainment that becomes dangerous when he crosses paths with a mysterious character.",
                "popularity": 14.331,
                "poster_path": "/3bX6VVSMf0dvzk5pMT4ALG5A92d.jpg",
                "release_date": "1999-04-02",
                "title": "Following",
                "video": False,
                "vote_average": 7.149,
                "vote_count": 1378,
                "credit_id": "52fe44739251416c750352fd",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "backdrop_path": "/t1NlvLU5xJamUTPVwnWi2o9nR76.jpg",
                "genre_ids": [53, 14, 9648],
                "id": 43629,
                "original_language": "en",
                "original_title": "Doodlebug",
                "overview": "In his squalid apartment, a man tries to squash with his shoe an insect of some kind that is moving around the room.",
                "popularity": 7.565,
                "poster_path": "/cXDFFv6yZNW3vUHOKKUPJNnL0So.jpg",
                "release_date": "1997-01-01",
                "title": "Doodlebug",
                "video": False,
                "vote_average": 6.5,
                "vote_count": 416,
                "credit_id": "52fe4655c3a36847f80f96c9",
                "department": "Writing",
                "job": "Writer",
            },
            {
                "adult": False,
                "backdrop_path": "/2PKMeD171nYXR3J77fD3GKl1zfl.jpg",
                "genre_ids": [28, 80, 18, 53],
                "id": 49026,
                "original_language": "en",
                "original_title": "The Dark Knight Rises",
                "overview": "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                "popularity": 89.834,
                "poster_path": "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
                "release_date": "2012-07-16",
                "title": "The Dark Knight Rises",
                "video": False,
                "vote_average": 7.778,
                "vote_count": 21187,
                "credit_id": "52fe4781c3a36847f813991b",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "backdrop_path": "/2PKMeD171nYXR3J77fD3GKl1zfl.jpg",
                "genre_ids": [28, 80, 18, 53],
                "id": 49026,
                "original_language": "en",
                "original_title": "The Dark Knight Rises",
                "overview": "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                "popularity": 89.834,
                "poster_path": "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
                "release_date": "2012-07-16",
                "title": "The Dark Knight Rises",
                "video": False,
                "vote_average": 7.778,
                "vote_count": 21187,
                "credit_id": "52fe4781c3a36847f8139915",
                "department": "Writing",
                "job": "Story",
            },
            {
                "adult": False,
                "backdrop_path": "/69EFgWWPFWbRNHmQgYdSnyJ94Ge.jpg",
                "genre_ids": [28, 12, 878],
                "id": 49521,
                "original_language": "en",
                "original_title": "Man of Steel",
                "overview": "A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.",
                "popularity": 77.65,
                "poster_path": "/dksTL9NXc3GqPBRHYHcy1aIwjS.jpg",
                "release_date": "2013-06-12",
                "title": "Man of Steel",
                "video": False,
                "vote_average": 6.612,
                "vote_count": 14229,
                "credit_id": "52fe4799c3a36847f813e655",
                "department": "Writing",
                "job": "Story",
            },
            {
                "adult": False,
                "backdrop_path": "/pbrkL804c8yAv3zBZR4QPEafpAR.jpg",
                "genre_ids": [12, 18, 878],
                "id": 157336,
                "original_language": "en",
                "original_title": "Interstellar",
                "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
                "popularity": 251.393,
                "poster_path": "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                "release_date": "2014-11-05",
                "title": "Interstellar",
                "video": False,
                "vote_average": 8.412,
                "vote_count": 32207,
                "credit_id": "5505e4dac3a36862e900346c",
                "department": "Writing",
                "job": "Writer",
            },
            {
                "adult": False,
                "backdrop_path": "/ddIkmH3TpR6XSc47jj0BrGK5Rbz.jpg",
                "genre_ids": [10752, 28, 18],
                "id": 374720,
                "original_language": "en",
                "original_title": "Dunkirk",
                "overview": "The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.",
                "popularity": 48.368,
                "poster_path": "/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg",
                "release_date": "2017-07-19",
                "title": "Dunkirk",
                "video": False,
                "vote_average": 7.456,
                "vote_count": 15341,
                "credit_id": "56819cc8c3a368607501004f",
                "department": "Writing",
                "job": "Writer",
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [18, 53, 35],
                "id": 456684,
                "original_language": "en",
                "original_title": "Larceny",
                "overview": "A man breaks into a flat, startling the occupant. They argue about the new girlfriend of the 'burglar', who's come  to get her stuff. Then a third man bursts out of the cupboard...",
                "popularity": 2.29,
                "poster_path": "/uL0iqPb4dtICVCCMKYem2yRPBRX.jpg",
                "release_date": "1996-07-14",
                "title": "Larceny",
                "video": False,
                "vote_average": 5.7,
                "vote_count": 7,
                "credit_id": "595dfc71c3a36828fc078efb",
                "department": "Writing",
                "job": "Writer",
            },
            {
                "adult": False,
                "backdrop_path": "/yY76zq9XSuJ4nWyPDuwkdV7Wt0c.jpg",
                "genre_ids": [28, 53, 878],
                "id": 577922,
                "original_language": "en",
                "original_title": "Tenet",
                "overview": "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                "popularity": 67.382,
                "poster_path": "/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
                "release_date": "2020-08-22",
                "title": "Tenet",
                "video": False,
                "vote_average": 7.196,
                "vote_count": 8596,
                "credit_id": "5da313b51967570011aa6486",
                "department": "Writing",
                "job": "Writer",
            },
            {
                "adult": False,
                "backdrop_path": "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
                "genre_ids": [18, 28, 80, 53],
                "id": 155,
                "original_language": "en",
                "original_title": "The Dark Knight",
                "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                "popularity": 97.428,
                "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                "release_date": "2008-07-14",
                "title": "The Dark Knight",
                "video": False,
                "vote_average": 8.511,
                "vote_count": 30351,
                "credit_id": "5f27d6a1d9403500375f670a",
                "department": "Writing",
                "job": "Story",
            },
            {
                "adult": False,
                "backdrop_path": "/qcx2OKadBD1abBsKRObHJvryvF0.jpg",
                "genre_ids": [10770, 27],
                "id": 804706,
                "original_language": "en",
                "original_title": "Tarantella",
                "overview": '"Tarantella" was an early Super 8 short film directed by Christopher Nolan with his childhood friend Roko Belic. It was made in 1989 while Nolan was studying at University College London. The film aired on "Image Union," a PBS programme in Chicago.  It is about the suffering of a young man while he has nightmare about spiders and demons.',
                "popularity": 3.682,
                "poster_path": "/7BJzoe7zCgZ3ADROZ4Ix4ycyD3S.jpg",
                "release_date": "1990-09-12",
                "title": "Tarantella",
                "video": False,
                "vote_average": 5.143,
                "vote_count": 21,
                "credit_id": "604a19075f622b006daa1ef4",
                "department": "Writing",
                "job": "Writer",
            },
            {
                "adult": False,
                "backdrop_path": None,
                "genre_ids": [16, 28, 53, 878],
                "id": 64956,
                "original_language": "en",
                "original_title": "Inception: The Cobol Job",
                "overview": 'This "Inception" prequel unfolds courtesy of a beautiful Motion Comic, and explains how Cobb, Arthur and Nash were enlisted by Cobol Engineering.',
                "popularity": 7.935,
                "poster_path": "/sNxqwtyHMNQwKWoFYDqcYTui5Ok.jpg",
                "release_date": "2010-12-07",
                "title": "Inception: The Cobol Job",
                "video": False,
                "vote_average": 7.255,
                "vote_count": 290,
                "credit_id": "60d40dad3c887d0076ef6313",
                "department": "Writing",
                "job": "Characters",
            },
            {
                "adult": False,
                "backdrop_path": "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
                "genre_ids": [28, 878, 12],
                "id": 27205,
                "original_language": "en",
                "original_title": "Inception",
                "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
                "popularity": 112.336,
                "poster_path": "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
                "release_date": "2010-07-15",
                "title": "Inception",
                "video": False,
                "vote_average": 8.364,
                "vote_count": 34276,
                "credit_id": "6168e57da802360043ef85d0",
                "department": "Writing",
                "job": "Writer",
            },
            {
                "adult": False,
                "backdrop_path": "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
                "genre_ids": [18, 36],
                "id": 872585,
                "original_language": "en",
                "original_title": "Oppenheimer",
                "overview": "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
                "popularity": 811.11,
                "poster_path": "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
                "release_date": "2023-07-19",
                "title": "Oppenheimer",
                "video": False,
                "vote_average": 8.265,
                "vote_count": 2088,
                "credit_id": "62e2e919fe077a005f06af53",
                "department": "Writing",
                "job": "Writer",
            },
        ],
    },
}
