{
    "adult": False,
    "backdrop_path": "/v6EUsxCZBksSmcomBcXErJZWL2I.jpg",
    "belongs_to_collection": None,
    "budget": 0,
    "genres": [{"id": 99, "name": "Documentary"}],
    "homepage": "",
    "id": 186567,
    "imdb_id": "tt5237190",
    "original_language": "en",
    "original_title": "Gotham Uncovered: Creation of a Scene",
    "overview": "Director Christopher Nolan and creative collaborators unmask the incredible detail and planning behind The Dark Knight, including stunt staging, filming in IMAX, the new Bat-Suit and Bat-Pod and other exclusive features.",
    "popularity": 1.544,
    "poster_path": "/lAAwYAEnDXJoYt1V0DUBkLJK8sh.jpg",
    "production_companies": [
        {
            "id": 14772,
            "logo_path": "/1XTIrcpK2JgnKn1RYgsPEJiUO0k.png",
            "name": "Warner Bros. Home Entertainment Group",
            "origin_country": "US",
        }
    ],
    "production_countries": [
        {"iso_3166_1": "GB", "name": "United Kingdom"},
        {"iso_3166_1": "US", "name": "United States of America"},
    ],
    "release_date": "2008-07-15",
    "revenue": 0,
    "runtime": 64,
    "spoken_languages": [
        {"english_name": "English", "iso_639_1": "en", "name": "English"}
    ],
    "status": "Released",
    "tagline": "",
    "title": "Gotham Uncovered: Creation of a Scene",
    "video": False,
    "vote_average": 7.0,
    "vote_count": 8,
    "credits": {
        "cast": [
            {
                "adult": False,
                "gender": 2,
                "id": 525,
                "known_for_department": "Directing",
                "name": "Christopher Nolan",
                "original_name": "Christopher Nolan",
                "popularity": 30.125,
                "profile_path": "/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg",
                "cast_id": 7,
                "character": "Self",
                "credit_id": "52fe4d009251416c7512c917",
                "order": 0,
            },
            {
                "adult": False,
                "gender": 2,
                "id": 3894,
                "known_for_department": "Acting",
                "name": "Christian Bale",
                "original_name": "Christian Bale",
                "popularity": 40.111,
                "profile_path": "/AcfW3p5D6ov573fABLyGqwYdolD.jpg",
                "cast_id": 8,
                "character": "Self",
                "credit_id": "52fe4d009251416c7512c91b",
                "order": 1,
            },
            {
                "adult": False,
                "gender": 2,
                "id": 3904,
                "known_for_department": "Editing",
                "name": "Lee Smith",
                "original_name": "Lee Smith",
                "popularity": 2.405,
                "profile_path": "/zlnK1i7CqdzIFTFqfMsYLyt2Sk8.jpg",
                "cast_id": 9,
                "character": "Self",
                "credit_id": "52fe4d009251416c7512c91f",
                "order": 2,
            },
            {
                "adult": False,
                "gender": 2,
                "id": 282,
                "known_for_department": "Production",
                "name": "Charles Roven",
                "original_name": "Charles Roven",
                "popularity": 1.22,
                "profile_path": "/4uJLoVstC1CBcArXFOe53N2fDr1.jpg",
                "cast_id": 10,
                "character": "Self",
                "credit_id": "52fe4d009251416c7512c923",
                "order": 3,
            },
            {
                "adult": False,
                "gender": 2,
                "id": 947,
                "known_for_department": "Sound",
                "name": "Hans Zimmer",
                "original_name": "Hans Zimmer",
                "popularity": 15.256,
                "profile_path": "/tpQnDeHY15szIXvpnhlprufz4d.jpg",
                "cast_id": 11,
                "character": "Self",
                "credit_id": "6415dc7a31032500e8a1b3f1",
                "order": 4,
            },
        ],
        "crew": [
            {
                "adult": False,
                "gender": 2,
                "id": 113913,
                "known_for_department": "Production",
                "name": "Jordan Goldberg",
                "original_name": "Jordan Goldberg",
                "popularity": 1.214,
                "profile_path": None,
                "credit_id": "52fe4cff9251416c7512c901",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "gender": 2,
                "id": 116232,
                "known_for_department": "Production",
                "name": "Jason Hillhouse",
                "original_name": "Jason Hillhouse",
                "popularity": 1.33,
                "profile_path": None,
                "credit_id": "52fe4d009251416c7512c907",
                "department": "Production",
                "job": "Producer",
            },
            {
                "adult": False,
                "gender": 2,
                "id": 959124,
                "known_for_department": "Editing",
                "name": "Michael Fallavollita",
                "original_name": "Michael Fallavollita",
                "popularity": 1.214,
                "profile_path": None,
                "credit_id": "52fe4d009251416c7512c90d",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "gender": 2,
                "id": 959124,
                "known_for_department": "Editing",
                "name": "Michael Fallavollita",
                "original_name": "Michael Fallavollita",
                "popularity": 1.214,
                "profile_path": None,
                "credit_id": "52fe4cff9251416c7512c8f5",
                "department": "Directing",
                "job": "Director",
            },
            {
                "adult": False,
                "gender": 0,
                "id": 1132127,
                "known_for_department": "Writing",
                "name": "Carl Jordan",
                "original_name": "Carl Jordan",
                "popularity": 0.6,
                "profile_path": None,
                "credit_id": "52fe4d009251416c7512c913",
                "department": "Writing",
                "job": "Screenplay",
            },
            {
                "adult": False,
                "gender": 0,
                "id": 1132127,
                "known_for_department": "Writing",
                "name": "Carl Jordan",
                "original_name": "Carl Jordan",
                "popularity": 0.6,
                "profile_path": None,
                "credit_id": "52fe4cff9251416c7512c8fb",
                "department": "Directing",
                "job": "Director",
            },
        ],
    },
}
